### ISSUE TITLE
Add wiki history link?

### ISSUE THREAD

**Issue by justinclift** [dorna-robotics/dorna#2]
Your work on the wiki is going well @smhty, it's looking good. :smile:

Would you be open to adding a "Wiki History" link to the bottom of the side bar, to make it easier for people to see what's changed since the last time they visited?

The kind of thing I'm meaning is like the bottom most link on the right hand sidebar here:

&nbsp; &nbsp; https://github.com/synthetos/g2/wiki

For yours, the link would be to: https://github.com/dorna-robotics/dorna//wiki/_history

:smile:

**Comment by smhty** [comment]
Thanks @justinclift 
As you suggested, I  made a costume toolbar with a link to the "Wiki history" page.

**Comment by smhty** [comment]
Fixed #2
