### ISSUE TITLE
_xyz_to_joint does not take units into account

### ISSUE THREAD

**Issue by mfogelson** [dorna-robotics/dorna#6]
I noticed today that _xyz_to_joint doesnt look at the units when solving the inverse kinematics.  This would be nice to add with in this method.

**Comment by smhty** [comment]
@mfogelson good point.

_xyz_to_joint and similar methods were set to work with inch, and as you mentioned before they intended to work as a private method. They also have a very restricted input format and  only accept numpy array.

For the next release of the API, I will write public functions that can accept several input formats, and also take into account the length unit system.
