### ISSUE TITLE
when I set units to mm, joint speed seems to be affected as well

### ISSUE THREAD

**Issue by mfogelson** [dorna-robotics/dorna#8]
When I send a play command like the one below, which moves fine when I do not change the units to mm, moves incredibly slow when I load a config with units set to mm:

```
 cmd1 = json.dumps({"command": "move", "prm": {"path": "joint", "movement": 0, "speed":1000, "j0": 90}, "fulfill": True})
robot.play(cmd1)
```

I checked through the api and don't see any issues with the speed being overwritten after loading a config with units = mm, but was wondering if you could also replicate this issue on your end.

**Comment by smhty** [comment]
@mfogelson 
Speed and unit system are always correlated.
When the unit system is "mm" then the speed unit is mm/min, and when the unit system is "inch" then the speed unit is inch/min.

For example, speed 1,000 inch/min in inch unit system is equivalent to the speed 25400 mm/min when you are in the "mm" domain.
Make sure to scale your speed accordingly (1 inch = 25.4 mm) when you are switching your unit system. 

Take a look at the code below, this is where the speed scales based on the length unit system: 
https://github.com/dorna-robotics/dorna/blob/bdf19c342722119e1e0a700b5cbe8220f87b73b6/dorna/api.py#L2455

**Comment by mfogelson** [comment]
My path is "joint" mode though. So it should still be degrees/min.

**Comment by smhty** [comment]
@mfogelson 
Good point, I made some changes in the _move method.
I tested it and it works fine for me now.
Let me know if you still see the problem.
https://github.com/dorna-robotics/dorna/blob/071b207e01eb78465e7da493f9c22aff76fd84e1/dorna/api.py#L2460
