### ISSUE TITLE
can you update the home command to append 

### ISSUE THREAD

**Issue by mfogelson** [dorna-robotics/dorna#9]
In
```
1052 def home(self, joint):
1053		if joint not in ["j0","j1", "j2", "j3", "j4"]:
1054 			return None 
1055											
1056		# homing
1057		# job_1: home
1058		command = {"command": "home", "prm": [joint]}		
1059                result = self.play(command, False)
```

Can you remove the append = False, or at least make it optional.

I am operating the Dorna in a confined space and It would be good if I could reposition the robot before homing certain joints.

**Comment by smhty** [comment]
@mfogelson 
For some internal difficulties and safety issues we decided to isolate the homing process.
One technique that I use when I want to isolate two or multiple tasks and make sure that they are not interrupting each other is to read `self._device`, or call `self.device()` in a while loop:

For example
```python
# play some commands
robot.play("some commands")

'''
track the robot state 
0: not busy and all the commands has been completed
1: still running some commands
'''
device = json.loads(robot.device())

while device["state"] != 0:
     # the robot state is 1, and something is still running
     time.sleep(0.001)
     device = json.loads(robot.device())

# the job has been done, and the robot state is 0
robot.home("home a specific joint")
```
